import requests

# The orchestrator runs on port 2000 by default
API_URL = "http://localhost:2000/generate"

def run_simple_sanity():
    """
    Minimal test to verify the FastAPI server is up and the 
    Qwen model is generating text correctly.
    """
    print("📡 Sending simple 'Hi' to the model...")
    
    payload = {
        "prompt": "Say 'Hello, I am ready to work!'",
        "max_new_tokens": 20,
        "test_name": "Simple_Sanity",
        "pipeline_mode": "llm" 
    }
    
    try:
        response = requests.post(API_URL, json=payload, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            # The 'response' key contains the text generated by the LLM
            print(f"\n✅ Server Response: {data.get('response', '').strip()}")
            print("\n✨ Connection successful. The model is responding.")
        else:
            print(f"\n❌ Server Error: {response.status_code}")
            print(f"Details: {response.text}")
            
    except requests.exceptions.ConnectionError:
        print("\n❌ Connection Failed: Is 'model_loader.py' running?")
    except Exception as e:
        print(f"\n❌ Unexpected Error: {e}")

if __name__ == "__main__":
    run_simple_sanity()